<a href="https://colab.research.google.com/github/Adityadeeenair/Fake-News-Prediction-model/blob/main/Fake_News_Prediction_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTING THE LIBRARIES**

In [13]:
import numpy as np
import pandas as pd
import re

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [14]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

**DATA PREPROCESSING :**

In [16]:
news = pd.read_csv("/content/train.csv")
news.title

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799                            What Keeps the F-35 Alive
Name: title, Length: 20800, dtype: object

In [17]:
news.shape

(20800, 5)

**CHECKING AND HANDLING MISSING VALUES :**

In [18]:
news.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [19]:
news = news.fillna(' ')

**MERGING AND MAKING A NEW COLUMN -> CONTENTS**

In [20]:
news['contents'] = news['author'] + ' ' + news['title']

In [21]:
print(news['contents'])

0        Darrell Lucus House Dem Aide: We Didn’t Even S...
1        Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2        Consortiumnews.com Why the Truth Might Get You...
3        Jessica Purkiss 15 Civilians Killed In Single ...
4        Howard Portnoy Iranian woman jailed for fictio...
                               ...
20795    Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796    Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma...
20797    Michael J. de la Merced and Rachel Abrams Macy...
20798    Alex Ansary NATO, Russia To Hold Parallel Exer...
20799              David Swanson What Keeps the F-35 Alive
Name: contents, Length: 20800, dtype: object

**SEPARATING THE DATA AND THE LABEL :**

In [22]:
X = news.drop(columns = 'label' , axis = 1 )
Y = news['label']

In [23]:
print(X)

          id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...
2          2                  Why the Truth Might Get You Fired
3          3  15 Civilians Killed In Single US Airstrike Hav...
4          4  Iranian woman jailed for fictional unpublished...
...      ...                                                ...
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797  20797  Macy’s Is Said to Receive Takeover Approach by...
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799  20799                          What Keeps the F-35 Alive

                                          author  \
0                                  Darrell Lucus
1                                Daniel J. Flynn
2                             Consortiumnews.com
3                                Jessica Purkiss
4                                 Howard Portnoy
...                                          ...
20795                              Jerome Hudson
20796                           Benjamin Hoffman
20797  Michael J. de la Merced and Rachel Abrams
20798                                Alex Ansary
20799                              David Swanson

                                                    text  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...
1      Ever get the feeling your life circles the rou...
2      Why the Truth Might Get You Fired October 29, ...
3      Videos 15 Civilians Killed In Single US Airstr...
4      Print \nAn Iranian woman has been sentenced to...
...                                                  ...
20795  Rapper T. I. unloaded on black celebrities who...
20796  When the Green Bay Packers lost to the Washing...
20797  The Macy’s of today grew from the union of sev...
20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799    David Swanson is an author, activist, journa...

                                                contents
0      Darrell Lucus House Dem Aide: We Didn’t Even S...
1      Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2      Consortiumnews.com Why the Truth Might Get You...
3      Jessica Purkiss 15 Civilians Killed In Single ...
4      Howard Portnoy Iranian woman jailed for fictio...
...                                                  ...
20795  Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796  Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma...
20797  Michael J. de la Merced and Rachel Abrams Macy...
20798  Alex Ansary NATO, Russia To Hold Parallel Exer...
20799            David Swanson What Keeps the F-35 Alive

[20800 rows x 5 columns]

In [24]:
print(Y)

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

**STEMMING** using **PorterStemmer**:

In [25]:
pstem = PorterStemmer()

In [26]:
def Stemmer(contents):
  Stemmed_data = re.sub('[^a-zA-Z]', ' ' , contents)
  Stemmed_data = Stemmed_data.lower()
  Stemmed_data = Stemmed_data.split()
  Stemmed_data = [pstem.stem(word) for word in Stemmed_data if not word in stopwords.words('english')]
  Stemmed_data = ' '.join(Stemmed_data)
  return Stemmed_data

In [27]:
news['contents'] = news['contents'].apply(Stemmer)

In [28]:
print(news['contents'])

0        darrel lucu hous dem aid even see comey letter...
1        daniel j flynn flynn hillari clinton big woman...
2                   consortiumnew com truth might get fire
3        jessica purkiss civilian kill singl us airstri...
4        howard portnoy iranian woman jail fiction unpu...
                               ...
20795    jerom hudson rapper trump poster child white s...
20796    benjamin hoffman n f l playoff schedul matchup...
20797    michael j de la merc rachel abram maci said re...
20798    alex ansari nato russia hold parallel exercis ...
20799                            david swanson keep f aliv
Name: contents, Length: 20800, dtype: object

**SEPARATING CONTENTS AND LABEL FROM THE DATASET :**

In [29]:
X = news['contents'].values
Y = news['label'].values

In [30]:
print(X)
print()
print(Y)

['darrel lucu hous dem aid even see comey letter jason chaffetz tweet'
 'daniel j flynn flynn hillari clinton big woman campu breitbart'
 'consortiumnew com truth might get fire' ...
 'michael j de la merc rachel abram maci said receiv takeov approach hudson bay new york time'
 'alex ansari nato russia hold parallel exercis balkan'
 'david swanson keep f aliv']

[1 0 1 ... 0 1 1]

In [31]:
print(X.shape, Y.shape)

(20800,) (20800,)

**CONVERTING TEXT DATA INTO NUMERIC DATA**

In [32]:
vect = TfidfVectorizer()
vect.fit(X)
X = vect.transform(X)

In [33]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 210687 stored elements and shape (20800, 17128)>
  Coords	Values
  (0, 267)	0.2701012497770876
  (0, 2483)	0.36765196867972083
  (0, 2959)	0.24684501285337127
  (0, 3600)	0.3598939188262558
  (0, 3792)	0.27053324808454915
  (0, 4973)	0.23331696690935097
  (0, 7005)	0.2187416908935914
  (0, 7692)	0.24785219520671598
  (0, 8630)	0.2921251408704368
  (0, 8909)	0.36359638063260746
  (0, 13473)	0.2565896679337956
  (0, 15686)	0.2848506356272864
  (1, 1497)	0.2939891562094648
  (1, 1894)	0.15521974226349364
  (1, 2223)	0.3827320386859759
  (1, 2813)	0.19094574062359204
  (1, 3568)	0.26373768806048464
  (1, 5503)	0.7143299355715573
  (1, 6816)	0.1904660198296849
  (1, 16799)	0.30071745655510157
  (2, 2943)	0.3179886800654691
  (2, 3103)	0.46097489583229645
  (2, 5389)	0.3866530551182615
  (2, 5968)	0.3474613386728292
  (2, 9620)	0.49351492943649944
  :	:
  (20797, 3643)	0.2115550061362374
  (20797, 7042)	0.21799048897828685
  (20797, 8364)	0.22322585870464115
  (20797, 8988)	0.36160868928090795
  (20797, 9518)	0.29542040034203126
  (20797, 9588)	0.17455348025522197
  (20797, 10306)	0.08038079000566466
  (20797, 12138)	0.24778257724396505
  (20797, 12344)	0.27263457663336677
  (20797, 13122)	0.24825263521976057
  (20797, 14967)	0.3115945315488075
  (20797, 15295)	0.08159261204402356
  (20797, 16996)	0.08315655906109998
  (20798, 350)	0.2844693781907258
  (20798, 588)	0.3112141524638974
  (20798, 1125)	0.4460515589182237
  (20798, 5032)	0.40837014502395297
  (20798, 6889)	0.3249628569429943
  (20798, 10177)	0.31924963701870285
  (20798, 11052)	0.4460515589182237
  (20798, 13046)	0.2236326748827061
  (20799, 377)	0.5677577267055112
  (20799, 3623)	0.37927626273066584
  (20799, 8036)	0.45983893273780013
  (20799, 14852)	0.5677577267055112

**SPLITTING THE DATA INTO TRAINING AND TESTING DATA**

In [34]:
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

**TRAINING THE LOGISTIC REGRESSION MODEL**

In [35]:
model = LogisticRegression()

In [36]:
model.fit(X_train, Y_train)  #Setting up the model

LogisticRegression()

In [37]:
import joblib

# Save artifacts
joblib.dump(model, "fake_news_model.joblib")
joblib.dump(vect, "tfidf_vectorizer.joblib")

print("Artifacts saved")

Artifacts saved

**EVALUATING THE MODEL**:

In [38]:
#Predicting the labels on training data
train_prediction = model.predict(X_train)

#Checking the accuracy score of predictions on training data
train_accuracy = accuracy_score(train_prediction, Y_train)

In [39]:
print("Accuracy of the training data :" , train_accuracy)

Accuracy of the training data : 0.9863581730769231

In [40]:
#Predicting the labels on testing data
test_prediction = model.predict(X_test)

#Checking the accuracy score of predictions on testing data
test_accuracy = accuracy_score(test_prediction, Y_test)

In [41]:
print("Accuracy of the testing data :" , test_accuracy)

Accuracy of the testing data : 0.9790865384615385

**MAKING A PREDICTIVE SYSTEM :**

In [43]:
input_news = "Avoiding Peanuts to Avoid an Allergy Is a Bad Strategy for Most The New York Times"


#preprocessing the input data
processed_text = Stemmer(input_news)

#converting text into numerical form using the trained vectorizer
vectorized_input = vect.transform([processed_text])

#Prediction
prediction = model.predict(vectorized_input)
print(prediction)

if prediction[0] == 0:
    print("The news is Real")
else:
    print("The news is Fake")

[0]
The news is Real